//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assets.Source.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arriving at {0}....
        /// </summary>
        internal static string ArrivingAt {
            get {
                return ResourceManager.GetString("ArrivingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Joss!! The local authorities have seized your Opium cargo and have also fined you {0}, Taipan!.
        /// </summary>
        internal static string AuthoritiesSeizedYourOpium {
            get {
                return ResourceManager.GetString("AuthoritiesSeizedYourOpium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad joss!! {0} of your bodyguards have been killed by cutthroats and you have been robbed of all of your cash, Taipan!!
        ///.
        /// </summary>
        internal static string BadJossYouHaveBeenRobbed {
            get {
                return ResourceManager.GetString("BadJossYouHaveBeenRobbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But we escaped from {0} of &apos;em!.
        /// </summary>
        internal static string ButWeEscapedFromXOfEm {
            get {
                return ResourceManager.GetString("ButWeEscapedFromXOfEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain&apos;s Report.
        /// </summary>
        internal static string CaptainsReport {
            get {
                return ResourceManager.GetString("CaptainsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///         Do you want to start . . .
        ///         1) With cash (and a debt)
        ///             &gt;&gt; or &lt;&lt;
        ///         2) With five guns and no cash
        ///             (But no debt!)
        ///        .
        /// </summary>
        internal static string CashOrGuns {
            get {
                return ResourceManager.GetString("CashOrGuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprador&apos;s Report.
        /// </summary>
        internal static string CompradorsReport {
            get {
                return ResourceManager.GetString("CompradorsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t lose &apos;em..
        /// </summary>
        internal static string CouldntLoseEm {
            get {
                return ResourceManager.GetString("CouldntLoseEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current seaworthiness: {0} ({1}%).
        /// </summary>
        internal static string CurrentSeaworthiness {
            get {
                return ResourceManager.GetString("CurrentSeaworthiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have business with Elder Brother Wu, the moneylender?.
        /// </summary>
        internal static string DoYouHaveBusinessWithElderBrotherWu {
            get {
                return ResourceManager.GetString("DoYouHaveBusinessWithElderBrotherWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want Elder Brother Wu to make up the difference for you?.
        /// </summary>
        internal static string DoYouWantElderBrotherWuToMakeUpTheDifference {
            get {
                return ResourceManager.GetString("DoYouWantElderBrotherWuToMakeUpTheDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to buy a ship&apos;s gun for {0}, Taipan? .
        /// </summary>
        internal static string DoYouWishToBuyAGun {
            get {
                return ResourceManager.GetString("DoYouWishToBuyAGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to trade in your damaged ship for one with 50 more capacity by paying an additional {0}, Taipan? .
        /// </summary>
        internal static string DoYouWishToTradeInYourShip_Damaged {
            get {
                return ResourceManager.GetString("DoYouWishToTradeInYourShip.Damaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to trade in your fine ship for one with 50 more capacity by paying an additional {0}, Taipan? .
        /// </summary>
        internal static string DoYouWishToTradeInYourShip_Fine {
            get {
                return ResourceManager.GetString("DoYouWishToTradeInYourShip.Fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elder Brother has given Li Yuen the difference between what he wanted and your cash on hand and added the same amount to your debt..
        /// </summary>
        internal static string ElderBrotherHasGivenLiYuenTheDifference {
            get {
                return ResourceManager.GetString("ElderBrotherHasGivenLiYuenTheDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elder Brother is aware of your plight, Taipan. He is willing to loan you an additional {0} if you will pay back {1}. Are you willing, Taipan?.
        /// </summary>
        internal static string ElderBrotherIsAwareOfYourPlight {
            get {
                return ResourceManager.GetString("ElderBrotherIsAwareOfYourPlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elder Brother Wu has sent {0} braves to escort you to the Wu mansion, Taipan..
        /// </summary>
        internal static string ElderBrotherWuSpiel_1 {
            get {
                return ResourceManager.GetString("ElderBrotherWuSpiel.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elder Brother Wu reminds you of the Confucian ideal of personal worthiness, and how this applies to paying one&apos;s debts..
        /// </summary>
        internal static string ElderBrotherWuSpiel_2 {
            get {
                return ResourceManager.GetString("ElderBrotherWuSpiel.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He is reminded of a fabled barbarian who came to a bad end, after not caring for his obligations. He hopes no such fate awaits you, his friend, Taipan..
        /// </summary>
        internal static string ElderBrotherWuSpiel_3 {
            get {
                return ResourceManager.GetString("ElderBrotherWuSpiel.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very well. Elder Brother Wu will not pay Li Yuen the difference.  I would be very wary of pirates if I were you, Taipan..
        /// </summary>
        internal static string ElderBrotherWuWillNotPayLiYuenTheDifference {
            get {
                return ResourceManager.GetString("ElderBrotherWuWillNotPayLiYuenTheDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good joss!! They let us be!!.
        /// </summary>
        internal static string GoodJossTheyLetUsBe {
            get {
                return ResourceManager.GetString("GoodJossTheyLetUsBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has dropped to {0}!!.
        /// </summary>
        internal static string HasDroppedToX {
            get {
                return ResourceManager.GetString("HasDroppedToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has risen to {0}!!.
        /// </summary>
        internal static string HasRisenToX {
            get {
                return ResourceManager.GetString("HasRisenToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He won&apos;t loan you so much, Taipan!.
        /// </summary>
        internal static string HeWontLoanYouSoMuch {
            get {
                return ResourceManager.GetString("HeWontLoanYouSoMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit &apos;em, but didn&apos;t sink &apos;em, Taipan!.
        /// </summary>
        internal static string HitEmButDidntSinkEm {
            get {
                return ResourceManager.GetString("HitEmButDidntSinkEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hostile ships approaching, Taipan!.
        /// </summary>
        internal static string HostileShipsApproaching {
            get {
                return ResourceManager.GetString("HostileShipsApproaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much, Taipan? .
        /// </summary>
        internal static string HowMuch {
            get {
                return ResourceManager.GetString("HowMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much do you wish to borrow?.
        /// </summary>
        internal static string HowMuchToBorrow {
            get {
                return ResourceManager.GetString("HowMuchToBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much {0} shall I move to the warehouse, Taipan?.
        /// </summary>
        internal static string HowMuchToMove {
            get {
                return ResourceManager.GetString("HowMuchToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much {0} shall I move aboard ship, Taipan?.
        /// </summary>
        internal static string HowMuchToMoveAboard {
            get {
                return ResourceManager.GetString("HowMuchToMoveAboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much do you wish to repay him?.
        /// </summary>
        internal static string HowMuchToRepay {
            get {
                return ResourceManager.GetString("HowMuchToRepay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much will you withdraw?.
        /// </summary>
        internal static string HowMuchToWithdraw {
            get {
                return ResourceManager.GetString("HowMuchToWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Och, &apos;tis a pity to be {0}% damaged. We can fix yer whole ship for {0}, or make partial repairs if you wish. How much will ye spend?.
        /// </summary>
        internal static string HowMuchWillYeSpend {
            get {
                return ResourceManager.GetString("HowMuchWillYeSpend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much will you deposit? .
        /// </summary>
        internal static string HowMuchWillYouDeposit {
            get {
                return ResourceManager.GetString("HowMuchWillYouDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much {0} shall I buy, Taipan: .
        /// </summary>
        internal static string HowMuchXShallIBuy {
            get {
                return ResourceManager.GetString("HowMuchXShallIBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arms.
        /// </summary>
        internal static string Item_Arms {
            get {
                return ResourceManager.GetString("Item.Arms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        internal static string Item_Everything {
            get {
                return ResourceManager.GetString("Item.Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Cargo.
        /// </summary>
        internal static string Item_General {
            get {
                return ResourceManager.GetString("Item.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opium.
        /// </summary>
        internal static string Item_Opium {
            get {
                return ResourceManager.GetString("Item.Opium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silk.
        /// </summary>
        internal static string Item_Silk {
            get {
                return ResourceManager.GetString("Item.Silk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    I think we&apos;re going down!!
        ///
        ///.
        /// </summary>
        internal static string IThinkWereGoingDown {
            get {
                return ResourceManager.GetString("IThinkWereGoingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger reports large theft from warehouse, Taipan..
        /// </summary>
        internal static string LargeTheftFromWarehouse {
            get {
                return ResourceManager.GetString("LargeTheftFromWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s hope we lose &apos;em, Taipan!.
        /// </summary>
        internal static string LetsHopeWeLoseEm {
            get {
                return ResourceManager.GetString("LetsHopeWeLoseEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Li Yuen asks {0} in donation to the temple of Tin Hau, the Sea Goddess.  Will you pay?.
        /// </summary>
        internal static string LiYuenAsksXInDonation {
            get {
                return ResourceManager.GetString("LiYuenAsksXInDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Li Yuen has sent a Lieutenant, Taipan.  He says his admiral wishes to see you in Hong Kong, posthaste!.
        /// </summary>
        internal static string LiYuenHasSentALieutenant {
            get {
                return ResourceManager.GetString("LiYuenHasSentALieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Li Yuen&apos;s fleet drove them off!.
        /// </summary>
        internal static string LiYuensFleetDroveThemOff {
            get {
                return ResourceManager.GetString("LiYuensFleetDroveThemOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Li Yuen&apos;s pirates, Taipan!!.
        /// </summary>
        internal static string LiYuensPirates {
            get {
                return ResourceManager.GetString("LiYuensPirates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At sea.
        /// </summary>
        internal static string Location_AtSea {
            get {
                return ResourceManager.GetString("Location.AtSea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batavia.
        /// </summary>
        internal static string Location_Batavia {
            get {
                return ResourceManager.GetString("Location.Batavia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong.
        /// </summary>
        internal static string Location_HongKong {
            get {
                return ResourceManager.GetString("Location.HongKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manila.
        /// </summary>
        internal static string Location_Manila {
            get {
                return ResourceManager.GetString("Location.Manila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagasaki.
        /// </summary>
        internal static string Location_Nagasaki {
            get {
                return ResourceManager.GetString("Location.Nagasaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saigon.
        /// </summary>
        internal static string Location_Saigon {
            get {
                return ResourceManager.GetString("Location.Saigon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shanghai.
        /// </summary>
        internal static string Location_Shanghai {
            get {
                return ResourceManager.GetString("Location.Shanghai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore.
        /// </summary>
        internal static string Location_Singapore {
            get {
                return ResourceManager.GetString("Location.Singapore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taipan, Mc Henry from the Hong Kong Shipyards has arrived!!  He says, &quot;I see ye&apos;ve a wee bit of damage to yer ship. Will ye be wanting repairs?.
        /// </summary>
        internal static string McHenryHasArrived {
            get {
                return ResourceManager.GetString("McHenryHasArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 {0} {1}.
        /// </summary>
        internal static string MidMonthDateFormat {
            get {
                return ResourceManager.GetString("MidMonthDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        internal static string Months_1 {
            get {
                return ResourceManager.GetString("Months.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        internal static string Months_10 {
            get {
                return ResourceManager.GetString("Months.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        internal static string Months_11 {
            get {
                return ResourceManager.GetString("Months.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        internal static string Months_12 {
            get {
                return ResourceManager.GetString("Months.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        internal static string Months_2 {
            get {
                return ResourceManager.GetString("Months.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        internal static string Months_3 {
            get {
                return ResourceManager.GetString("Months.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        internal static string Months_4 {
            get {
                return ResourceManager.GetString("Months.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string Months_5 {
            get {
                return ResourceManager.GetString("Months.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        internal static string Months_6 {
            get {
                return ResourceManager.GetString("Months.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        internal static string Months_7 {
            get {
                return ResourceManager.GetString("Months.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        internal static string Months_8 {
            get {
                return ResourceManager.GetString("Months.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        internal static string Months_9 {
            get {
                return ResourceManager.GetString("Months.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fight.
        /// </summary>
        internal static string Orders_Fight {
            get {
                return ResourceManager.GetString("Orders.Fight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Orders_Run {
            get {
                return ResourceManager.GetString("Orders.Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw Cargo.
        /// </summary>
        internal static string Orders_ThrowCargo {
            get {
                return ResourceManager.GetString("Orders.ThrowCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string PortActivity_Buy {
            get {
                return ResourceManager.GetString("PortActivity_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Trading.
        /// </summary>
        internal static string PortActivity_QuitTrading {
            get {
                return ResourceManager.GetString("PortActivity_QuitTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retire.
        /// </summary>
        internal static string PortActivity_Retire {
            get {
                return ResourceManager.GetString("PortActivity_Retire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        internal static string PortActivity_Sell {
            get {
                return ResourceManager.GetString("PortActivity_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Cargo.
        /// </summary>
        internal static string PortActivity_TransferCargo {
            get {
                return ResourceManager.GetString("PortActivity_TransferCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Bank.
        /// </summary>
        internal static string PortActivity_VisitBank {
            get {
                return ResourceManager.GetString("PortActivity_VisitBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compradore.
        /// </summary>
        internal static string Rating_Compradore {
            get {
                return ResourceManager.GetString("Rating_Compradore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galley Hand.
        /// </summary>
        internal static string Rating_GalleyHand {
            get {
                return ResourceManager.GetString("Rating_GalleyHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Taipan.
        /// </summary>
        internal static string Rating_MasterTaipan {
            get {
                return ResourceManager.GetString("Rating_MasterTaipan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma Tsu.
        /// </summary>
        internal static string Rating_MaTsu {
            get {
                return ResourceManager.GetString("Rating_MaTsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taipan.
        /// </summary>
        internal static string Rating_Taipan {
            get {
                return ResourceManager.GetString("Rating_Taipan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shall I Buy, Sell, or Quit trading? .
        /// </summary>
        internal static string ShallIBuySellOrQuitTrading {
            get {
                return ResourceManager.GetString("ShallIBuySellOrQuitTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shall I Buy, Sell, Visit bank, Transfer cargo, or Quit trading? .
        /// </summary>
        internal static string ShallIBuySellVisitBankTransferCargoOrQuitTrading {
            get {
                return ResourceManager.GetString("ShallIBuySellVisitBankTransferCargoOrQuitTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shall I Buy, Sell, Visit bank, Transfer cargo, Quit trading, or Retire? .
        /// </summary>
        internal static string ShallIBuySellVisitBankTransferCargoQuitTradingOrRetire {
            get {
                return ResourceManager.GetString("ShallIBuySellVisitBankTransferCargoQuitTradingOrRetire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ship attacking, Taipan!.
        /// </summary>
        internal static string ShipsAttacking_One {
            get {
                return ResourceManager.GetString("ShipsAttacking.One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ships attacking, Taipan!.
        /// </summary>
        internal static string ShipsAttacking_Other {
            get {
                return ResourceManager.GetString("ShipsAttacking.Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        internal static string Status_Critical {
            get {
                return ResourceManager.GetString("Status.Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair.
        /// </summary>
        internal static string Status_Fair {
            get {
                return ResourceManager.GetString("Status.Fair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string Status_Good {
            get {
                return ResourceManager.GetString("Status.Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect.
        /// </summary>
        internal static string Status_Perfect {
            get {
                return ResourceManager.GetString("Status.Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        internal static string Status_Poor {
            get {
                return ResourceManager.GetString("Status.Poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime.
        /// </summary>
        internal static string Status_Prime {
            get {
                return ResourceManager.GetString("Status.Prime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm, Taipan!!
        ///
        ///.
        /// </summary>
        internal static string Storm {
            get {
                return ResourceManager.GetString("Storm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunk {0} of the buggers, Taipan!.
        /// </summary>
        internal static string SunkXOfTheBuggers {
            get {
                return ResourceManager.GetString("SunkXOfTheBuggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buggers got us, Taipan!!!
        ///It&apos;s all over, now!!!.
        /// </summary>
        internal static string TheBuggersGotUs {
            get {
                return ResourceManager.GetString("TheBuggersGotUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buggers hit a gun, Taipan!!.
        /// </summary>
        internal static string TheBuggersHitAGun {
            get {
                return ResourceManager.GetString("TheBuggersHitAGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taipan!!  The price of {0}.
        /// </summary>
        internal static string ThePriceOfX {
            get {
                return ResourceManager.GetString("ThePriceOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s nothing there, Taipan!.
        /// </summary>
        internal static string TheresNothingThere {
            get {
                return ResourceManager.GetString("TheresNothingThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They&apos;re firing on us, Taipan!.
        /// </summary>
        internal static string TheyreFiringOnUs {
            get {
                return ResourceManager.GetString("TheyreFiringOnUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very well, Taipan, the game is over!.
        /// </summary>
        internal static string VeryWellGameOver {
            get {
                return ResourceManager.GetString("VeryWellGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very well, Taipan. Good joss!!.
        /// </summary>
        internal static string VeryWellGoodJoss {
            get {
                return ResourceManager.GetString("VeryWellGoodJoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your warehouse is full, Taipan!.
        /// </summary>
        internal static string WarehouseIsFull {
            get {
                return ResourceManager.GetString("WarehouseIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your warehouse will only hold an additional {0}, Taipan!.
        /// </summary>
        internal static string WarehouseWillOnlyHoldX {
            get {
                return ResourceManager.GetString("WarehouseWillOnlyHoldX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We captured some booty. It&apos;s worth {0}!.
        /// </summary>
        internal static string WeCapturedSomeBooty {
            get {
                return ResourceManager.GetString("WeCapturedSomeBooty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We got away from &apos;em, Taipan!.
        /// </summary>
        internal static string WeGotAwayFromEm {
            get {
                return ResourceManager.GetString("WeGotAwayFromEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We got &apos;em all, Taipan!.
        /// </summary>
        internal static string WeGotEmAll {
            get {
                return ResourceManager.GetString("WeGotEmAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have no guns, Taipan!!.
        /// </summary>
        internal static string WeHaveNoGuns {
            get {
                return ResourceManager.GetString("WeHaveNoGuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aye, we&apos;ll fight &apos;em, Taipan..
        /// </summary>
        internal static string WellFightEm {
            get {
                return ResourceManager.GetString("WellFightEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aye, we&apos;ll run, Taipan..
        /// </summary>
        internal static string WellRun {
            get {
                return ResourceManager.GetString("WellRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We made it!.
        /// </summary>
        internal static string WeMadeIt {
            get {
                return ResourceManager.GetString("WeMadeIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     We made it!!
        ///
        ///.
        /// </summary>
        internal static string WeMadeIt2 {
            get {
                return ResourceManager.GetString("WeMadeIt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re firing on &apos;em, Taipan!.
        /// </summary>
        internal static string WereFiringOnThem {
            get {
                return ResourceManager.GetString("WereFiringOnThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re going down, Taipan!!
        ///.
        /// </summary>
        internal static string WereGoingDown {
            get {
                return ResourceManager.GetString("WereGoingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve been blown off course to {0}.
        /// </summary>
        internal static string WeveBeenBlownOffCourseTo {
            get {
                return ResourceManager.GetString("WeveBeenBlownOffCourseTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve been hit, Taipan!!.
        /// </summary>
        internal static string WeveBeenHit {
            get {
                return ResourceManager.GetString("WeveBeenHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you wish me to buy, Taipan?.
        /// </summary>
        internal static string WhatDoYouWishMeToBuy {
            get {
                return ResourceManager.GetString("WhatDoYouWishMeToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What shall I throw overboard, Taipan? .
        /// </summary>
        internal static string WhatShallIThrowOverboard {
            get {
                return ResourceManager.GetString("WhatShallIThrowOverboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taipan, what shall we do??    (f=fight, r=run, t=throw cargo).
        /// </summary>
        internal static string WhatShallWeDo {
            get {
                return ResourceManager.GetString("WhatShallWeDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taipan,.
        /// </summary>
        internal static string WhatWillYouNameYourFirm_1 {
            get {
                return ResourceManager.GetString("WhatWillYouNameYourFirm.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will you name your Firm:.
        /// </summary>
        internal static string WhatWillYouNameYourFirm_2 {
            get {
                return ResourceManager.GetString("WhatWillYouNameYourFirm.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taipan, do you wish me to go to: 1) Hong Kong, 2) Shanghai, 3) Nagasaki, 4) Saigon, 5) Manila, 6) Singapore, or 7) Batavia ?.
        /// </summary>
        internal static string WhereToGo {
            get {
                return ResourceManager.GetString("WhereToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ran away, Taipan!.
        /// </summary>
        internal static string XRanAway {
            get {
                return ResourceManager.GetString("XRanAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ships of Li Yuen&apos;s pirate fleet, Taipan!!.
        /// </summary>
        internal static string XShipsOfLiYuensPirateFleet {
            get {
                return ResourceManager.GetString("XShipsOfLiYuensPirateFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already here, Taipan..
        /// </summary>
        internal static string YouAreAlreadyHere {
            get {
                return ResourceManager.GetString("YouAreAlreadyHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can afford {0}.
        /// </summary>
        internal static string YouCanAffordX {
            get {
                return ResourceManager.GetString("YouCanAffordX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taipan, you do not have enough cash!!.
        /// </summary>
        internal static string YouDoNotHaveEnoughCash {
            get {
                return ResourceManager.GetString("YouDoNotHaveEnoughCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Joss!! You&apos;ve been beaten up and robbed of {0} in cash, Taipan!!.
        /// </summary>
        internal static string YouGotRobbed {
            get {
                return ResourceManager.GetString("YouGotRobbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no cargo, Taipan..
        /// </summary>
        internal static string YouHaveNoCargo {
            get {
                return ResourceManager.GetString("YouHaveNoCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have only {0}, Taipan..
        /// </summary>
        internal static string YouHaveOnlyX {
            get {
                return ResourceManager.GetString("YouHaveOnlyX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the following on board, Taipan:
        ///Opium: {0}
        ///Silk: {1}
        ///Arms: {2}
        ///General: {3}
        ///.
        /// </summary>
        internal static string YouHaveTheFollowingOnBoard {
            get {
                return ResourceManager.GetString("YouHaveTheFollowingOnBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taipan, you only have {0} in cash..
        /// </summary>
        internal static string YouOnlyHaveXInCash {
            get {
                return ResourceManager.GetString("YouOnlyHaveXInCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taipan, you only have {0} in the bank..
        /// </summary>
        internal static string YouOnlyHaveXInTheBank {
            get {
                return ResourceManager.GetString("YouOnlyHaveXInTheBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your orders are to: {0}.
        /// </summary>
        internal static string YourOrdersAreTo {
            get {
                return ResourceManager.GetString("YourOrdersAreTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ship is overloaded, Taipan!!.
        /// </summary>
        internal static string YourShipIsOverloaded {
            get {
                return ResourceManager.GetString("YourShipIsOverloaded", resourceCulture);
            }
        }
    }
}
